### ISSUE TITLE
Canvas gauge and ng-repeat

### ISSUE THREAD

**Issue by rathervague** [dec/angular-canvas-gauge#5]
I have an issue with rendering the gauge when it is part of an ng-repeat.
The gauges appear to be in the DOM but are not displayed on the page.

Is there a special technique to get the canvas gauges render within an ng-repeat?

Your help is much appreciated.

**Comment by dec** [comment]
Hello,

I never try to place the appropiate markup inside an AngularJS repeat directive, then it's difficult to say something, however, if you can view the Gauge, but not the expected Gauge's values, then maybe we are talking about some problem with the scope of the variables you are trying to use?

Can you provide some plunker sample?

**Comment by rathervague** [comment]
Thanks for the feedback, for now I'm using a different component (ui-knob). I'll re-investigate this when I have more time. Cheers.

**Comment by dec** [comment]
Hello!

Just as you wanted!

**Comment by mdford** [comment]
Hi, I am experiencing the same issue as @rathervague .  I did create a plunker sample for you to look at:  
[https://plnkr.co/edit/c3G5twuCENO3lXY3fKm6]

I created 2 different gauges at the top of index.html to make sure I had it working and to also make sure it would use the values from a list.

```javascript
   width="{{nodes[0].width}}"
   height="{{nodes[0].height}}"
   data-value="{{nodes[0].value}}"
```

Then, below those I created 2 new gauges inside an ng-repeat

```html
<div ng-repeat="node in nodes">
    node: {{$index}}
    <canvas canvas-gauge
       id="myCanvas3"
       width="{{node.width}}"
       height="{{node.height}}"
       data-value="{{node.value}}"
       data-title="Speed"
       data-min-value="0"
       data-max-value="220"
       data-major-ticks="0 20 40 60 80 100 120 140 160 180 200 220"
       data-minor-ticks="2"
    ></canvas>
</div>
```

It looks like the second gauge is not created, but what appears to be happening is that BOTH gauges get created in the same spot (where gauge 1 is).  You can very briefly see the first (larger) gauge created before it is overwritten by gauge 2.

My theory, is that this is happening because both have the same id (myCanvas3).   

So, I then modified the js to create a _dynamic_ id 
```html
<canvas canvas-gauge
    id="myCanvas3-{{$index}}"
...
```
But, that causes issues.  **None** of the gauges inside the ng-repeat get created and it throws an error.  You cannot see it in the plunker, but when I debug in my local code, I get the following console error:

```TypeError: Cannot read property 'getContext' of null```

at the line ` ctx = canvas.getContext('2d')` in 

```javascript
 //noinspection JSUnresolvedVariable
    var
        canvas = config.renderTo.tagName ?
            config.renderTo : document.getElementById(config.renderTo),
        ctx = canvas.getContext('2d'),
        pxRatio = window.devicePixelRatio || 1,
        cache, CW, CH, CX, CY, max, cctx;
```

Just for completeness, here is the whole error stack (from my local code which is doing the same as the plunker):

```javascript
TypeError: Cannot read property 'getContext' of null
    at new Gauge (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:127489:21)
    at Object.link (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:128840:17)
    at http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:1247:18
    at invokeLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:9934:9)
    at nodeLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:9335:11)
    at compositeLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:8620:13)
    at compositeLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:8623:13)
    at compositeLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:8623:13)
    at compositeLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:8623:13)
    at publicLinkFn (http://127.0.0.1:8000/static/angular/dyehouse/js/dyehouse.packages.js:8500:30) <canvas canvas-gauge="" id="vm.myGauge-{{$index}}" data-type="radial-gauge" data-min-value="0" data-max-value="220" data-major-ticks="0 20 40 60 80 100 120 140 160 180 200 220" data-minor-ticks="2" data-highlights="0 40 #eee, 40 80 #ddd, 80 120 #ccc, 120 160 #aaa, 160 200 #eaa, 200 211.5 #f99, 211.5 220 #f00" width="{{vm.myGauge.width}}" height="{{vm.myGauge.height}}" data-value="22">
```

I hope I was thorough enough but please let me know if I can provide additional information to help debug and fix this issue.

Regards,

Mark

**Comment by dec** [comment]
Hello Mark,

Certainly I did not test the directive inside a repeat... however, what do you think if you try to use the original project without this directive? I think they can be a solution: the author test it with Angular 1 and 2 and apparently the Canvas Gauge can be used "as is"... so you can try it!

https://github.com/Mikhus/canvas-gauges

P.S. I am sorry but also don't have the required time right now to take a look Mark...

**Comment by JayNaire** [comment]
I can confirm that ng-repeat (and ng-show/hide) give problems (gauges not being drawn or updating).

**Comment by chandankumardn** [comment]
even i am facing same issue,,,, m not able to create the angular gouge inside ng-repaet.... guys any suggestion please....
